# Generated by Django 4.2.2 on 2023-07-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
