# Generated by Django 4.2.2 on 2023-07-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
