# Generated by Django 4.2.2 on 2023-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_hotel_rename_tourpackage_place_placevideo_placefood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cover',
            field=models.ImageField(null=True, upload_to='placeimage/'),
        ),
    ]
