# Generated by Django 4.2.2 on 2023-08-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_place_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.place'),
        ),
    ]
