# Generated by Django 4.2.2 on 2023-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_hotel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='conact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
