# Generated by Django 4.2.2 on 2023-08-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_hotel_conact_hotel_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='conact',
            new_name='contact',
        ),
    ]
