# Generated by Django 4.2.2 on 2023-08-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_conact_hotel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='placefood',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placefood',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placevideo',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
