# Generated by Django 4.2.2 on 2023-08-06 15:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_placefood_description_placefood_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=2, null=True)),
                ('photo', models.ImageField(null=True, upload_to='guides/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.place')),
            ],
        ),
    ]
