# Generated by Django 4.2.2 on 2023-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
