# Generated by Django 4.2.2 on 2023-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_guide_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
