# Generated by Django 4.2.2 on 2023-08-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_division_package_alter_guide_phone_place_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('DHAKA', 'Dhaka Division'), ('BARISAL', 'Barisal Division'), ('KHULNA', 'Khulna Divison'), ('MYMENSINGH', 'Mymensingh Division'), ('RAJSHAHI', 'Rajshahi Division'), ('RANGPUR', 'Rangpur Divison'), ('SYLHET', 'Sylhet Division'), ('CHITTAGONG', 'Chittagong')], max_length=30, unique=True),
        ),
    ]
