# Generated by Django 4.2.2 on 2023-08-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_package_cover_package_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
