# Generated by Django 4.2.2 on 2023-08-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='persons',
            field=models.IntegerField(default=1),
        ),
    ]
