# Generated by Django 4.2.2 on 2023-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_booking_package_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='seats',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
