# Generated by Django 4.2.2 on 2023-08-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_package_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='space',
        ),
    ]
