# Generated by Django 4.2.2 on 2023-08-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_remove_booking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='remaining_seats',
            field=models.IntegerField(null=True),
        ),
    ]
