# Generated by Django 4.2.2 on 2023-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_blog_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='add_to_nav',
            field=models.BooleanField(default=False),
        ),
    ]
