# Generated by Django 4.2.2 on 2023-08-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_place_add_to_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
    ]
