# Generated by Django 4.2.2 on 2023-08-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_remove_place_duration_remove_place_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
