# Generated by Django 4.2.2 on 2023-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeculture',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
