# Generated by Django 4.2.2 on 2023-08-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_placeculture_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
    ]
